name: Release Build

# Trigger only when tags matching v*.*.* are pushed
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Prevent runaway builds

    steps:
      # Step 1: Checkout code with full history
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Restore build cache (speeds up subsequent builds)
      - name: Cache Buildozer
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      # Step 3: Generate changelog
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Update version in buildozer.spec
      - name: Update Version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Updating version to: $VERSION"
          sed -i "s/^version = .*/version = $VERSION/" buildozer.spec
          grep "^version" buildozer.spec

      # Step 5: Free disk space (GitHub runners have limited space)
      - name: Free Disk Space
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          echo "Disk space after cleanup:"
          df -h

      # Step 6: Build APK using Docker
      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v "$(pwd)":/app \
            -w /app \
            kivy/buildozer \
            buildozer android debug

          # Fix permissions (Docker runs as root)
          sudo chown -R $USER:$USER .buildozer || true
          sudo chown -R $USER:$USER bin || true

      # Step 7: Find the built APK
      - name: Find APK
        id: find_apk
        run: |
          APK_PATH=$(find bin -name "*.apk" -type f | head -1)
          if [ -z "$APK_PATH" ]; then
            echo "Error: No APK found in bin/"
            ls -R bin/
            exit 1
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Found APK: $APK_PATH"
          ls -lh "$APK_PATH"

      # Step 8: Create GitHub Release with APK
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Release Notes

            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            1. Download the APK below
            2. Enable "Install from Unknown Sources" on your Android device
            3. Install the APK
            4. Open Habit Tracker

            ## Device Compatibility

            - Android 7.0 (API 24) or higher
            - ARM64-v8a architecture (tested on Honor Magic6)
          draft: true
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v0.') }}
          files: ${{ env.APK_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Notify on failure
      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Build failed!"
          echo "Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
